# Generated by Django 3.2.8 on 2021-12-03 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_coupen_redeemedcoupen'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedcoupen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
