# Generated by Django 3.2.8 on 2021-12-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_redeemedcoupen_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupen',
            name='valid_to',
            field=models.DateField(),
        ),
    ]
