# Generated by Django 3.2.8 on 2021-12-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_auto_20211205_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='coupen_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
