# Generated by Django 3.2.8 on 2021-12-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('vendor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('brand_name', models.CharField(max_length=60, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='photos/logo')),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['brand_name'],
            },
        ),
    ]
