# Generated by Django 3.2.8 on 2021-12-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_redeemed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
